version: '2'
services:

  
  www:
    build: www/.
    ports:
      - "80:5000"
    links:
      - db
    depends_on:
      - db
    volumes:
      - \Users\ashay\Desktop\Development\git\flask:\app
  db:
    build: db/.
    volumes:
      - \Users\ashay\Desktop\Development\git\flask\db:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: admin